# Generated by Django 5.2.6 on 2025-11-22 22:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('unidad', models.CharField(default='kg', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, help_text='Cantidad disponible actualmente', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.DecimalField(decimal_places=2, help_text='Umbral mínimo para generar alerta de stock', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_ocupado_bodega', models.DecimalField(decimal_places=2, default=0, help_text='% de capacidad de bodega usado (opcional)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='LoteGallinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(max_length=60)),
                ('cantidad_gallinas', models.PositiveIntegerField(help_text='Número de gallinas del lote', validators=[django.core.validators.MinValueValidator(1)])),
                ('edad_semanas', models.PositiveIntegerField(help_text='Edad promedio del lote en semanas', validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_alimento', models.CharField(choices=[('INICIO', 'Inicio'), ('ENGORDE', 'Engorde'), ('POSTURA', 'Postura')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertas_stock', models.BooleanField(default=True)),
                ('notificar_proyecciones', models.BooleanField(default=True)),
                ('modo_oscuro_automatico', models.BooleanField(default=False)),
                ('permitir_descargas', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_avicola', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('CRITICO', 'Crítico'), ('BAJO', 'Bajo'), ('INFO', 'Informativo')], max_length=10)),
                ('mensaje', models.CharField(max_length=255)),
                ('dias_restantes', models.IntegerField(blank=True, help_text='Días estimados de stock restante (opcional)', null=True)),
                ('porcentaje_restante', models.DecimalField(blank=True, decimal_places=2, help_text='% de stock restante (opcional)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='panel.insumo')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_a_proyectar', models.PositiveIntegerField(help_text='Cantidad de días de la proyección', validators=[django.core.validators.MinValueValidator(1)])),
                ('consumo_diario_kg', models.DecimalField(decimal_places=2, help_text='Consumo diario estimado (kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_proyectado_kg', models.DecimalField(decimal_places=2, help_text='Consumo total proyectado (kg)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='panel.insumo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Racion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField(default=django.utils.timezone.now)),
                ('cantidad_total_kg', models.DecimalField(decimal_places=2, help_text='Cantidad total de alimento (kg) para el lote', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_algas', models.DecimalField(decimal_places=2, help_text='% de algas en la mezcla', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('porcentaje_carbonato', models.DecimalField(decimal_places=2, help_text='% de carbonato de calcio en la mezcla', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raciones', to='panel.lotegallinas')),
            ],
            options={
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('origen', models.CharField(blank=True, help_text="Ej: 'creado manual', 'importado', etc.", max_length=60)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
