# Generated by Django 5.2.8 on 2025-12-17 02:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('unidad', models.CharField(default='kg', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_ocupado_bodega', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='LoteGallinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(max_length=60)),
                ('cantidad_gallinas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('edad_semanas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_alimento', models.CharField(choices=[('INICIO', 'Inicio'), ('ENGORDE', 'Engorde'), ('POSTURA', 'Postura')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionHuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_huevo', models.CharField(choices=[('PEQUEÑO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande'), ('EXTRA_GRANDE', 'Extra Grande')], default='MEDIANO', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_animal', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('granos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('algas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dias', models.CharField(max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertas_stock', models.BooleanField(default=True)),
                ('notificar_proyecciones', models.BooleanField(default=True)),
                ('modo_oscuro_automatico', models.BooleanField(default=False)),
                ('permitir_descargas', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_avicola', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('CRITICO', 'Crítico'), ('BAJO', 'Bajo'), ('INFO', 'Informativo')], max_length=10)),
                ('mensaje', models.CharField(max_length=255)),
                ('dias_restantes', models.IntegerField(blank=True, null=True)),
                ('porcentaje_restante', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='panel.insumo')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_a_proyectar', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('consumo_diario_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_proyectado_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='panel.insumo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Racion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField(default=django.utils.timezone.now)),
                ('cantidad_total_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_algas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('porcentaje_carbonato', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raciones', to='panel.lotegallinas')),
            ],
            options={
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionRacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_animales', models.PositiveIntegerField()),
                ('periodo_dias', models.PositiveIntegerField()),
                ('unidad_racion', models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos')], max_length=2)),
                ('total_granos_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_algas_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_carbonato_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_granos_ahorro_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_algas_ahorro_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_carbonato_ahorro_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ahorro_granos_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ahorro_algas_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ahorro_carbonato_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ahorro_total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('racion_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='panel.registroracion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('origen', models.CharField(blank=True, max_length=60)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReporteDiarioHuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, help_text='Comentarios opcionales sobre el día (ej: comportamiento de las gallinas, consumo de alimento, etc.)', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Diario de Huevos',
                'verbose_name_plural': 'Reportes Diarios de Huevos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
