# Generated by Django 5.2.8 on 2025-12-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteDiarioHuevos',
        ),
    ]
